name: "Slider CI"

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  iOS:
    name: Build Slider 
    runs-on: macOS-latest
    timeout-minutes: 10
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro"]
    steps:
      - uses: actions/checkout@v2           
      - name: Set Xcode version
        run: sudo xcode-select -s $DEVELOPER_DIR
      - name: iOS - Test Build
        run: xcodebuild -project "Slider.xcodeproj" -scheme "SliderScheme" -destination "${{ matrix.destination }}" build test
        timeout-minutes: 10
