name: "Slider CI"

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  iOS:
    name: Build Slider 
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
      - uses: futureware-tech/simulator-action@v3
        with:
          os: 'iOS'
          os_version: '>= 14.0'
      uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: Slider.xcodeproj
          scheme: Slider
          destination: platform=iOS
          action: test
      timeout-minutes: 10
